name: webapp-boilerplate
channels:
- defaults
dependencies:
- attrs=17.4.0
- ca-certificates=2017.08.26
- certifi=2018.1.18
- decorator=4.2.1
- flake8=3.5.0
- ipython=6.2.1
- ipython_genutils=0.2.0
- jedi=0.11.1
- libedit=3.1
- libffi=3.2.1
- mccabe=0.6.1
- ncurses=6.0
- openssl=1.0.2n
- parso=0.1.1
- pexpect=4.4.0
- pickleshare=0.7.4
- pip=9.0.1
- pluggy=0.6.0
- prompt_toolkit=1.0.15
- ptyprocess=0.5.2
- py=1.5.2
- pycodestyle=2.3.1
- pyflakes=1.6.0
- pygments=2.2.0
- pytest=3.4.0
- python=3.6.4
- readline=7.0
- setuptools=38.5.1
- simplegeneric=0.8.1
- six=1.11.0
- sqlite=3.22.0
- tk=8.6.7
- traitlets=4.3.2
- wcwidth=0.1.7
- wheel=0.30.0
- xz=5.2.3
- zlib=1.2.11
- pip:
  - click==6.7
  - flask==0.12.2
  - flask-graphql==1.4.1
  - graphene==2.0.1
  - graphene-sqlalchemy==2.0.0
  - graphql-core==2.0
  - graphql-relay==0.4.5
  - ipdb==0.11
  - ipython-genutils==0.2.0
  - iso8601==0.1.12
  - itsdangerous==0.24
  - jinja2==2.10
  - markupsafe==1.0
  - promise==2.1
  - prompt-toolkit==1.0.15
  - rx==1.6.0
  - singledispatch==3.4.0.3
  - snapshottest==0.5.0
  - sqlalchemy==1.1.15
  - termcolor==1.1.0
  - typing==3.6.2
  - werkzeug==0.13
